repo: 'responsive-navigation'
canvasCourse: 'web-dev-1'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - box-sizing
  - body-margin-0
  - responsive-css
  - responsive-font-sizes
  - nav-hover
  - screenshots-all

html:
  - path: 'index.html'
    has:
      - 'header > h1 + nav > ul > li > a'
    search:
      - 'Quetzalcoatlus'
      - 'Environment'
      - 'Dimensions'
      - 'Diet'
      - 'Flight'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font', 'normal 100%/1.3 sans-serif']
      - 'header'
      - 'h1'
      - 'nav ul'
      - 'nav li'
      - 'nav a'
      - 'nav a:hover'
      - ['@25', 'nav li']
